# Be sure to change these!
base_url = "https://revinderdev.github.io/"
title = "RevinderDev Blog"

# Sass compilation is required
compile_sass = true

# Optional: enable tags
taxonomies = [{ name = "tags" }]

# Code highlighting
[markdown]
highlight_code = true
highlight_theme = "gruvbox-dark"

[extra]

accent_color = "gruvbox"
background_color = "gruvbox"

logo_text = "Revinder"
favicon = "/fav-icon.png"
author = "Revinder"

menu_items = [
    { name = "Blog", url = "$BASE_URL" },

    { name = "Tags", url = "$BASE_URL/tags" },
    { name = "Archive", url = "$BASE_URL/archive" },
    { name = "About me", url = "$BASE_URL/about" },

    { name = "GitHub", url = "https://github.com/RevinderDev", newtab = true },
]

enable_post_view_navigation = true
post_view_navigation_prompt = "Thanks for reading! Read other posts?"
use_full_hack_font = true
page_titles = "main_only"
